version: 1
disable_existing_loggers: False

formatters:
  detailed:
    format: '%(asctime)s [%(levelname)s] [%(name)s:%(funcName)s:%(lineno)d] %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  simple:
    format: '%(levelname)s: %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: detailed
    stream: ext://sys.stdout
  rotating_file:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    formatter: detailed
    filename: app.log
    maxBytes: 10485760  # 10 MB
    backupCount: 5
    encoding: utf8

loggers:
  myapp:
    handlers: [console, rotating_file]
    level: DEBUG
    propagate: False

root:
    handlers: [console, rotating_file]
    level: DEBUG
